name: Ivan's
markdown: redcarpet
highlighter: pygments

comments:
    provider: disqus
    disqus :
      short_name : ivanw

analytics:
    provider: google
    google:
        tracking_id: UA-61682249-1

