name: Ivan's
kramdown:
  input: GFM
  syntax_highlighter: rouge

comments:
    provider: disqus
    disqus :
      short_name : ivanw

analytics:
    provider: google
    google:
        tracking_id: UA-61682249-1

